export default async (req, res) => {
    const { catId } = req.query;
    let articleList = [
        {
            "id": "1",
            "title": "Article 1",
            "alias": "article-1",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "05/05/2021",
            "category": "1",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "2",
            "title": "Article 2",
            "alias": "article-2",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "2",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "3",
            "title": "Article 3",
            "alias": "article-3",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "3",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "4",
            "title": "Article 4",
            "alias": "article-4",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "1",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "5",
            "title": "Article 5",
            "alias": "article-5",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "3",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "6",
            "title": "Article 6",
            "alias": "article-6",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "1",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "7",
            "title": "Article 7",
            "alias": "article-7",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "1",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "8",
            "title": "Article 8",
            "alias": "article-8",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "1",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "9",
            "title": "Article 9",
            "alias": "article-9",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "1",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "10",
            "title": "Article 10",
            "alias": "article-10",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "2",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "11",
            "title": "Article 11",
            "alias": "article-11",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "3",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "12",
            "title": "Article 12",
            "alias": "article-12",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "3",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "14",
            "title": "Article 14",
            "alias": "article-14",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "1",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "15",
            "title": "Article 15",
            "alias": "article-15",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "2",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        },
        {
            "id": "16",
            "title": "Article 16",
            "alias": "article-16",
            "image": "/images/article.jpg",
            "imageDetail": ["/images/article.jpg", "/images/article.jpg"],
            "publishDate": "06/05/2021",
            "category": "3",
            "MainInfo": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere. Aenean semper nulla sem, nec eleifend neque maximus ut. Sed hendrerit tincidunt tortor eu feugiat. Quisque tempus ante non consectetur placerat. Nullam eros nunc, fermentum feugiat dictum efficitur, tristique nec massa. Donec finibus urna a fermentum suscipit. Sed gravida dolor id mauris vulputate feugiat. Aliquam sodales suscipit metus, elementum feugiat ante laoreet quis. Etiam facilisis orci in hendrerit fermentum. Quisque sed aliquam magna. Curabitur suscipit, tortor vel laoreet bibendum, leo arcu lacinia enim, eget tincidunt sem erat in mauris. Morbi sodales erat ultrices blandit euismod.</p><p>Donec ornare elementum magna vel porta. Curabitur ante ante, accumsan eu metus eget, dictum faucibus tortor. Etiam sapien massa, ornare gravida suscipit ac, iaculis efficitur sem. Quisque a tempor sapien. Suspendisse scelerisque blandit magna, in rhoncus ex sollicitudin at. Nullam cursus justo nec augue venenatis consectetur. Aenean ultrices at libero et vestibulum. Nam quis risus auctor, lobortis nulla eleifend, fringilla massa. Cras lectus risus, ultricies et lacus in, venenatis dictum lorem. Etiam dapibus venenatis massa.</p><p>Praesent non ultrices urna. Curabitur vulputate mi eu ultricies tempor. Vestibulum tellus quam, congue et convallis eu, tincidunt eu tellus. Nulla condimentum nisi sodales sapien ornare venenatis. Duis ac tristique tortor. Donec eget risus pellentesque, tristique turpis sed, facilisis massa. Fusce ut facilisis mauris, sed eleifend tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur pharetra at nibh in placerat. Donec vulputate mattis arcu lacinia laoreet. Cras ut vulputate lacus. Integer at diam eget metus sollicitudin consectetur quis luctus erat. Integer et orci in sem sollicitudin sollicitudin. Vivamus in ultrices eros, et condimentum ante.</p>",
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus imperdiet finibus. Integer scelerisque vitae purus vel posuere. Etiam aliquet lectus vitae leo viverra, a pretium lorem posuere.",
            "status": true
        }
    ];

    const data = articleList.filter((item) => {
        return item.category == catId;
    });

    res.status(200).json(data)
}